### ISSUE TITLE
Add MDNS so the IP doesn't need to be typed

### ISSUE THREAD

**Issue by yutarour** [TennisBowling/arduinofest-queue#2]
## Why add MDNS?
- MDNS allows the user to type in a more simple address instead of the 255.255.255.255:3000 address every time. 
- Instead it will allow the user to type something like: signup.local in order to just access the server. 

## How to do it?
- Node has a mdns package. <https://www.npmjs.com/package/mdns>

## Alternative
- You could make this service hosted on a web server with a domain and host it there. However, you will have to add a period selection button here to allow students to select which period they are in.

**Comment by TennisBowling** [comment]
This is meant to be served behind an nginx instance or some other reverse proxy. The nginx instance should face the internet and should reverse proxy into the :3000 node server.
